INSERT INTO SAMPLE(ID, NAME, DESCRIPTION, USE_YN, REG_USER) VALUES('1','카테고리명1','설명1','1','등록자1');
INSERT INTO SAMPLE(ID, NAME, DESCRIPTION, USE_YN, REG_USER) VALUES('2','카테고리명2','설명2','2','등록자2');
INSERT INTO SAMPLE(ID, NAME, DESCRIPTION, USE_YN, REG_USER) VALUES('3','카테고리명3','설명3','1','등록자3');
INSERT INTO IDS VALUES('SAMPLE',175);