CREATE TABLE SAMPLE (
	ID VARCHAR(16) NOT NULL PRIMARY KEY,
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(100),
	USE_YN CHAR(1),
	REG_USER VARCHAR(10),
	REG_DATE DATE NOT NULL DEFAULT CURRENT_DATE()
);

CREATE TABLE IDS (
	TABLE_NAME VARCHAR(16) NOT NULL PRIMARY KEY
	,NEXT_ID DECIMAL(30) NOT NULL
);